fix(margin): fix display of rating block - INNO-908
ec-europa/ema-styleguide pull request #19
Opened 2018-02-01 09:40 UTC by emeryro

Small fix for content page template

2018-02-01 09:41 UTC, HAL-Patch-INNO commented
Deploy preview for *ema-styleguide* ready!

Built with commit 15e9a4a38d9183ad832f16460ca748b18dfe2c46

https://deploy-preview-19--ema-styleguide.netlify.com

2018-02-19 07:51 UTC, raduchiriac commented on framework/components/ema-headers/ema-headers.config.js
> +      alt: 'EMA logoss',
Fix this small typo

2018-02-19 08:01 UTC, raduchiriac requested changes

2018-02-19 08:01 UTC, raduchiriac commented on framework/utilities/ema-u-width/ema-u-width.scss
> +      width: auto !important;
Is `!important` really necessary?

2018-02-19 09:56 UTC, raduchiriac approved these changes

2018-02-19 09:56 UTC, merged