feat(footer): add component - INNO-878
ec-europa/ema-styleguide pull request #8
Opened 2018-01-16 12:31 UTC by emeryro

Add component for footer

2018-01-16 12:33 UTC, HAL-Patch-INNO commented
Deploy preview for *ema-styleguide* ready!

Built with commit 7b524f13e79ea955d905ce3c51631560b7bcd9c6

https://deploy-preview-8--ema-styleguide.netlify.com

2018-01-16 12:34 UTC, HAL-Patch-INNO commented
Deploy preview for *ema-styleguide* ready!

Built with commit 4af4952a822fc1c413b7d65e1eb419bde2d65d75

https://deploy-preview-8--ema-styleguide.netlify.com

2018-01-17 12:49 UTC, degliwe requested changes
![image](https://user-images.githubusercontent.com/965868/35043462-0f2a6ac6-fb8d-11e7-93da-fad6146b8e20.png)

On mobile, the EC logo should be floating on the right.

2018-01-23 07:03 UTC, degliwe approved these changes

2018-01-23 07:03 UTC, merged